//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBitsBites.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int id_factura { get; set; }
        public Nullable<int> id_pedido { get; set; }
        public Nullable<System.DateTime> fecha_factura { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual Pedidos Pedidos { get; set; }
    }
}
